server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heima?serverTimezone=UTC
    username: root
    password: "11"
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
#    开启驼峰转换
    map-underscore-to-camel-case: false
  type-aliases-package: cn.itcast.hotel.pojo


#  mybatis-plus:
#    global-config:
#      db-config:
#        table-prefix: tbl_

  global-config:
    db-config:
      table-prefix: tb_